[package]
name = "alex"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"

[features]
parallel = []
rayon-parallel = ["rayon", "parallel"]

default = ["rayon-parallel"]

[dependencies]
bumpalo = { version = "3.2", features = ["collections"] }
log = "0.4"
parking_lot = "0.10"
rayon = { version = "1.3", optional = true }
smallvec = "1.0"
