[package]
name = "alex"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"

[features]
parallel = ["parking_lot"]
faster = []

[dependencies]
bumpalo = { version = "3.2", features = ["collections"] }
log = "0.4"
smallvec = "1.0"
lazy_static = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = { version = "1.3", optional = true }
parking_lot = { version = "0.10", optional = true }

[dev-dependencies]
cfg-if = "*"
instant = { version = "*", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
env_logger = "*"
raw-cpuid = "*"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = { version = "=0.2.60", features = [] }
console_log = "*"
